# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /code

# copy the project files to the working directory
COPY . .

# install dependencies
RUN pip install -r requirements.txt

EXPOSE 5000 

# command to run on container start
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]