# set base image (host OS)
FROM jupyter/scipy-notebook:latest

# set the working directory in the container
WORKDIR /home/jovyan/work/

# copy the project files to the working directory
COPY . .

# install dependencies
#RUN pip install -r requirements.txt
