apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyter
    spec:
      hostname: jupyter
      containers:
        - name: jupyter
          image: ezambomsantana/jupyter
          volumeMounts:
          - mountPath: /opt/workspace
            name: volume
          ports:
            - containerPort: 8888
          env:
            - name: SPARK_MASTER_HOST
              value: spark-main
            - name: SPARK_MASTER_PORT
              value: "7077"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: task-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app.kubernetes.io/name: jupyter
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app.kubernetes.io/name: jupyter